// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WosiData;

namespace WosiData.Migrations
{
    [DbContext(typeof(WosuContext))]
    [Migration("20180815222530_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WosiDomain.BodyPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("BodyParts");
                });

            modelBuilder.Entity("WosiDomain.BodyPartMovement", b =>
                {
                    b.Property<int>("BodyPartId");

                    b.Property<int>("MovementId");

                    b.HasKey("BodyPartId", "MovementId");

                    b.HasIndex("MovementId");

                    b.ToTable("BodyPartMovement");
                });

            modelBuilder.Entity("WosiDomain.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MovementId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("WosiDomain.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("WosiDomain.BodyPartMovement", b =>
                {
                    b.HasOne("WosiDomain.BodyPart", "BodyPart")
                        .WithMany("BodyPartMovements")
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WosiDomain.Movement", "Movement")
                        .WithMany("BodyPartMovements")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WosiDomain.Equipment", b =>
                {
                    b.HasOne("WosiDomain.Movement", "Movement")
                        .WithMany("Equipment")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
